services:
  - type: web
    name: gp-backend
    env: node
    region: frankfurt  # or oregon/dublin based on your location
    plan: free
    rootDir: backend
    buildCommand: npm install && npx prisma generate
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false

  - type: web
    name: gp-frontend
    env: node
    region: frankfurt
    plan: free
    rootDir: frontend
    buildCommand: npm install && npm run build
    startCommand: npx serve -s dist -l 3000
    envVars:
      - key: VITE_API_URL
        value: https://gp-backend.onrender.com/api
