import { api } from "./api";

/** Upload the XLSX plan; body = FormData(file, establishmentId, kind='student'|'staff') */
export function importMealPlan(formData) {
  // No leading slash!
  return api.post("plans/import", formData, {
    headers: { "Content-Type": "multipart/form-data" },
  });
}

/** Optional: download a sample XLSX generated by backend */
export function downloadSample({ kind = "student" } = {}) {
  return api.get("plans/sample", { params: { kind }, responseType: "blob" });
}
